name: AI Google Ads Agent Daily Run

on:
  schedule:
    - cron: "0 8 * * *"  # runs every day at 8:00 UTC
  workflow_dispatch:      # allow manual trigger

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run AI agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_ADS_YAML: ${{ secrets.GOOGLE_ADS_YAML }}
          CUSTOMER_ID: ${{ secrets.CUSTOMER_ID }}
        run: |
          echo "$GOOGLE_ADS_YAML" > google-ads.yaml
          python3 main.py
